### PR TITLE
color sliders work and sfinv tabs are as well

### PR DESCRIPTION
**Pull request by monk-afk**
To address issue #10 , if i understand the report correctly, it was to make the color sliders work with sfinv and not break the tabs?

image

### CODE REVIEW

**Comment by MrRar** [comment]
With this PR, the color sliders aren't draggable. The purpose of form_send_job is to not refresh the form until the user has finished dragging the scroll bar. If the form gets resent to the user while the user is dragging the scroll bar, the user will lose their grip on the scrollbar.

To my knowledge everything is working fine already with the sfinv branch. Did you find something that wasn't working?

**Comment by monk-afk** [comment]
I see, my apologies for misunderstanding the previous issue (#10).

Unfortunately the scroll bar values are sent to the server immediately from the client, making dynamic refresh impossible. As you can see, when the server receives the value, the scroll box is set to the value's location on the bar once the formspec is refreshed.

What I had understood from the previous issue ticket, was the tab menu in sfinv were not showing in the skin selection menu.

**Comment by monk-afk** [comment]
Hello again,

I believe the latest commit to this pull is more in-line with the vision of this mod. The sliders are not stopped, and freely move until released, then the skin is updated.

However, I just realized that issue #10 is concerning the main branch, and as you say this branch was working fine previously. I totally misunderstood, my mistake.

I'll see if the method applied with this commit can also be used on the main branch, or try to figure a solution.

**Comment by monk-afk** [comment]
Closing stale PR

**Pull request closed without merging**
